ilanguage: ruby
rvm:
- 2.2
script:
- bundle exec rake production buildfinal travis
branches:
  only:
  - master
before_script:
- npm install -g bower
- bower install
env:
  global:
    secure: GzSRbooIimOmFd9CVHSe6KBQfWFsQNdZdkRw32OXZOAh4xMMMraJKuqxvomPYfeDIUyV9vwacQcHvQ+wCPK2FVYut03BGcu3Oi7vEwXzKeArkMEW/5DMq+so6GCH5OAxV1kmbaSQd9YGDcT/bbdsU3JRdaNgyfMUNrUX8zcekXCLesbYBTbQtZTtoPEE9KrZ/xCcmHMZ88yumd+JPXR8vxWaA/Rsf+gqOwPaUZ3YJ/Tu2nyrU50reUboR1XX32dBxfv0/tWejjz53sQBGz03YDW60Lw/qpJhnTZmDai2IJDd6xmfNmpjhNzUngYVfdouKh6TEwwU42uEcIVV0IFkWuAXPyBCkZi+79CXNyi2EZoLM8sQHfGbXtya2NrVD30bpGgccAAjsMrB3cXVzHBwONHMV7p8KmKlkGeyqyYW9g4abJQer2AFt4IECwJ4R+aUCtfvv6ToZDiG1yMR2ftD0+M1QWBVc556eWjlVViAN3ZocuKpVin8zNa9oJz405AWSpWwX+J85T19QXSJo97Cf3QdZBi5nKRLG81kDyRaRioA/njiCeeiHWi+Tf9ABBZt5/Xi4EKEeiwosj4uq2CTDZnKWHkV+c9JnUmk//BDn8hLi4tVrs7hopjIctPny9uUN5jJLLGXzF6fyfGML/RIa8OatqP4UbQmaQ7Mwphzdl4=
