ilanguage: ruby
rvm:
- 2.2
script:
- bundle exec rake production buildfinal travis
branches:
  only:
  - master
before_script:
- npm install -g bower
- bower install
env:
  global:
    secure: uyZRKwpfKMYaax6IfM+FUgYulINo3Fm1vLtaPvXWVRzloaBwSnRDuKKhftciZJqIc2bs66dj4Fnm59Jdd9c7eac9YE6tLIKSutgtzFZXoVKWwX+i7aEDm95g34kI+NHeqNqEQ+W5FC2bZwh4nEOGcFE5lo+iagR4YQfrYzHtCRmfAtkx1+Bhr6EoY1o7r+t/epN7CoZqsiOGRbK9I1Y3VNl34E9c75AvhccJb6X1Ks0Js0/YX6RWRMC5Odv2OQ9Oy5v/gPxiaBvp4iFuI57YuoaUn3dZnkqu5/rXmFX3cGpkJJRc9BKzgdZylvDkrqScvDgAmIyq/h2tJviaxVy8EJKRLhdwbp/HUAor1rTRLErizIa0YVKM2fmNdkynRbAQGOU2MAjO6QG2U5rx+nrWjUd7x57xUyy9yP8CTDvVtt9hJD3osKky+JXDAXOmJc8XAl+A06JnXbw+daGvTx8DDf8Wn47Y9DwYLYm1ygcpeLabBrx9d8cnyPtW69K2zgI+6TUr5Cq9ppKq6XuE7kL5QoiP0OMfvrMJDB5nurkJoNj4oYLm2soL9byN6imfXBq8hmV+cKXcS88qKINrEdHXc6wjAFwFTxnrqq0Zjx9Tmo5c8Vao3YywPHNSLa+LK7stFqA7FxPdrBecaoVxLxp3xtHBEMhHxQcDV0COsfJGtOI=
