# Site settings
title: DiamanteDesk Documentation
url: "http://docs.diamantedesk.com"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: pygments
exclude: [Gemfile, Gemfile.lock, Rakefile, README.md, bower.json]
lunr_search:
  strip_index_html: true
documentation:
  repository: http://github.com/eltrino/diamantedesk-documentation
  alias:
    master: latest
  ignore: ["gh-pages"]
analytics:
  universal:
    id: UA-53130831-2
    site: docs.diamantedesk.com
mode: development
sitemap:
    file: "/sitemap.xml"
    change_frequency_name: "daily"
    priority_name: "0.5"
