
name: Generate Documentation

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Prepare
        run: |
          - npm install -g bower
          - bower install
          - bundle install

      - name: Build
        run: bundle exec rake production buildfinal
